eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: register
server:
  port: 1010