eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka/
spring:
  application:
    name: router
server:
  port: 1030
zuul:
  routes:
    test: 
      path: /test/
      url: forward:/

